### ISSUE TITLE
สอบถามการดำเนินงานโปรเจคครับ

### ISSUE THREAD

**Issue by armhansa** [it-kmitl-2018/group1#5]
ขอคำแนะนำหน่อยครับ เกี่ยวกับเรื่องการใช้ Spring Boot ครับ
พี่ๆแนะนำให้ใช้ Spring Boot มั้ยครับ หรือว่าไม่ต้องใช้ก็สามารถทำ MicroServices ได้เหมือนกันครับ

ขอบคุณครับ

**Comment by champillon** [comment]
จริงๆแล้วไม่จำเป็นครับ แต่ถ้าใช้ Java หรือ Kotlin ส่วนใหญ่ Spring Boot จะมีคนทำเยอะสุดครับ แล้วก็จะ search google เจอ มากสุดครับ
